### PR TITLE
Remove inherited properties and get tests to work

### PR DESCRIPTION
**Pull request by connernilsen**

### CODE REVIEW

**Review by liammoyn — APPROVED** [review]
So was the test failed to run error just a versioning thing?

**Comment by connernilsen** [comment]
Lmao yeah @liammoyn. I think two versions for the same library were specified, so I turned all related versions into properties

**Review by jackblanc — APPROVED** [review]
Looks good, thanks for doing this. Can you make sure this propagates to HATS and SFTT? I'll handle LLB cause that's still a big WIP.

**Comment by connernilsen** [comment]
Sure

**Pull request merged**
